/**
 * Decision Agent Service
 *
 * Synthesizes all upstream agent findings (Vision, Document, Invoice Verification, Fault, Warranty)
 * into a structured, evidence-backed resolution recommendation.
 *
 * HARD GOVERNANCE RULE:
 * This agent recommends only. It has no authority to finalize a claim.
 * Every recommendation generated by this agent is marked with a mandatory disclaimer
 * and requires human Warranty Manager review and final decision authority.
 */

import {
  DecisionAgentResult,
  DocumentAgentResult,
  FaultAgentResult,
  InvoiceVerificationResult,
  RecommendationType,
  VisionAgentResult,
  WarrantyAgentResult,
} from "@/types";

export interface DecisionAgentInputs {
  visionResult: VisionAgentResult;
  documentResult: DocumentAgentResult;
  invoiceVerification: InvoiceVerificationResult;
  faultResult: FaultAgentResult;
  warrantyResult: WarrantyAgentResult;
}

export async function run(inputs: DecisionAgentInputs): Promise<DecisionAgentResult> {
  await new Promise((resolve) => setTimeout(resolve, 300));

  const { visionResult, documentResult, invoiceVerification, faultResult, warrantyResult } =
    inputs;

  // 1. Check for unverified or fraudulent invoice
  if (invoiceVerification.status === "MISMATCH" || invoiceVerification.status === "UNVERIFIED") {
    return {
      agentName: "DECISION",
      recommendation: "REQUEST_MORE_INFORMATION",
      confidence: 0.65,
      summary:
        "Invoice could not be verified against the authorized retailer database. Requesting verified proof of purchase.",
      reason: "Invoice verification failed or discrepancies detected with authorized seller registry.",
      keyEvidence: [
        `Invoice status: ${invoiceVerification.status}`,
        ...invoiceVerification.discrepancies,
      ],
      policyBasis: "Arbiter Verification Protocol Sec 1.4 — Proof of Purchase Authentication",
      suggestedRemedy: "REQUEST_MORE_INFORMATION",
      disclaimer: "AI RECOMMENDATION ONLY — REQUIRES HUMAN MANAGER FINAL APPROVAL",
      generatedAt: new Date().toISOString(),
    };
  }

  // 2. Check for physical damage exclusion
  if (
    visionResult.damageDetected &&
    (visionResult.damageType === "PHYSICAL_IMPACT" || faultResult.physical_damage_related)
  ) {
    // If warranty agent also confirms exclusion
    return {
      agentName: "DECISION",
      recommendation: "DENY",
      confidence: 0.97,
      summary:
        "Physical impact damage and screen fractures detected. Standard manufacturer warranty explicitly excludes accidental and external impact damage.",
      reason: "Physical damage detected by Vision and Fault agents, which is an excluded policy category.",
      keyEvidence: [
        "Vision Agent identified mechanical shock fracture pattern",
        "Fault categorized as User Accidental / Physical Impact",
        "Policy Section 4.1 explicitly excludes physical drops and damage",
      ],
      policyBasis: "Laptop Policy Sec 4.1 — Accidental & Physical Impact Exclusions",
      suggestedRemedy: "DENY",
      disclaimer: "AI RECOMMENDATION ONLY — REQUIRES HUMAN MANAGER FINAL APPROVAL",
      generatedAt: new Date().toISOString(),
    };
  }

  // 3. Check for expired warranty
  if (!warrantyResult.isWithinWarranty) {
    return {
      agentName: "DECISION",
      recommendation: "DENY",
      confidence: 0.96,
      summary:
        "The standard warranty period has expired. Claim cannot be approved under standard manufacturer warranty terms.",
      reason: `Warranty expired on ${warrantyResult.expirationDate}.`,
      keyEvidence: [
        `Purchase date ${warrantyResult.purchaseDate || documentResult.purchaseDate}`,
        `12-month coverage window expired on ${warrantyResult.expirationDate}`,
        "Customer is eligible for paid repair / battery service program",
      ],
      policyBasis: "Laptop Policy Sec 1.0 — Coverage Window Expiration",
      suggestedRemedy: "DENY",
      disclaimer: "AI RECOMMENDATION ONLY — REQUIRES HUMAN MANAGER FINAL APPROVAL",
      generatedAt: new Date().toISOString(),
    };
  }

  // 4. Valid hardware failure scenario -> REPLACE or REPAIR
  let remedy: RecommendationType = "REPLACE";
  if (faultResult.severity === "LOW") {
    remedy = "REPAIR";
  }

  return {
    agentName: "DECISION",
    recommendation: remedy,
    confidence: 0.94,
    summary:
      "Valid invoice verified from authorized retailer, authentic serial number, zero physical damage detected, and hardware defect is fully covered under the active 12-month policy.",
    reason: "Fully covered hardware component defect on genuine product within active warranty window.",
    keyEvidence: [
      `Authorized invoice ${documentResult.orderNumber || documentResult.invoice_number} verified from ${documentResult.retailer || documentResult.seller}`,
      "Visual inspection confirmed zero impact trauma or liquid ingress",
      "Internal hardware component defect verified by Fault Agent",
      `Active warranty policy (${warrantyResult.warrantyPeriodMonths} months) covers component replacement`,
    ],
    policyBasis: "Laptop Policy Sec 2.1 — Component Defect Replacement",
    suggestedRemedy: remedy,
    disclaimer: "AI RECOMMENDATION ONLY — REQUIRES HUMAN MANAGER FINAL APPROVAL",
    generatedAt: new Date().toISOString(),
  };
}
